In [22]:
# import pydytuesday

# pydytuesday.get_date('2025-08-12')

In [23]:
import pandas as pd

data = pd.read_csv('attribution_studies.csv')

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_name         744 non-null    object
 1   event_period       735 non-null    object
 2   event_year         592 non-null    object
 3   study_focus        744 non-null    object
 4   iso_country_code   520 non-null    object
 5   cb_region          744 non-null    object
 6   event_type         744 non-null    object
 7   classification     744 non-null    object
 8   summary_statement  744 non-null    object
 9   publication_year   744 non-null    int64
 10  citation           743 non-null    object
 11  source             744 non-null    object
 12  rapid_study        744 non-null    object
 13  link               744 non-null    object
dtypes: int64(1), object(13)
memory usage: 81.5+ KB

In [25]:
data.study_focus.value_counts()

study_focus
Event    593
Trend    151
Name: count, dtype: int64

In [26]:
(
    data[['publication_year']]
    .value_counts()
    .reset_index()
    .sort_values(by='publication_year', ascending=True)
)

    publication_year  count
17              2004      1
15              2005      1
16              2006      1
14              2007      3
12              2011     10
13              2012      9
11              2013     31
10              2014     32
6               2015     58
4               2016     62
7               2017     41
3               2018     80
9               2019     35
8               2020     41
1               2021     92
0               2022     95
5               2023     61
2               2024     91

In [27]:
data.event_type.value_counts()

event_type
Heat                207
Rain & flooding     177
Drought             106
Storm                61
Cold, snow & ice     57
Impact               33
Compound             33
Wildfire             31
Oceans               25
Atmosphere            7
Sunshine              4
River flow            3
Name: count, dtype: int64

In [30]:
data.cb_region.value_counts()

cb_region
Europe                              165
Eastern and south-eastern Asia      161
Northern America                    137
Global                               63
Sub-Saharan Africa                   56
Australia and New Zealand            49
Central and southern Asia            36
Latin America and the Caribbean      32
Northern hemisphere                  15
Arctic                               11
Northern Africa and western Asia      8
Oceania                               8
Antarctica                            3
Name: count, dtype: int64

In [31]:
data.iso_country_code

0      NaN
1      NaN
2      NaN
3      NaN
4      RUS
      ...
739    CHN
740    CHN
741    AUS
742    NaN
743    CHN
Name: iso_country_code, Length: 744, dtype: object

In [32]:
data

,event_name,event_period,event_year,study_focus,iso_country_code,cb_region,event_type,classification,summary_statement,publication_year,citation,source,rapid_study,link
0,European summer heatwave,2003,2003,Event,NaN,Europe,Heat,More severe or more likely to occur,"""We estimate it is very likely (confidence lev...",2004,"Stott, P. et al., 2004: Human contribution to ...",Nature,No,https://www.nature.com/nature/journal/v432/n70...
1,Global temperature extremes,since 1950,NaN,Trend,NaN,Global,Heat,More severe or more likely to occur,"""Comparing these observations with climate mod...",2005,"Christidis, N. et al., 2005: Detection of chan...",Geophysical Research Letters,No,https://agupubs.onlinelibrary.wiley.com/doi/fu...
2,Record warm autumn in Europe,2006,2006,Event,NaN,Europe,Heat,More severe or more likely to occur,"""Global warming has made a warm autumn like th...",2007,"Van Oldenborgh, G-J. et al., 2007: How unusual...",Climate of the Past,No,http://www.clim-past.net/3/659/2007/cp-3-659-2...
3,Increasing frequency of 'very warm' Northern h...,1860-2009,NaN,Trend,NaN,Northern hemisphere,Heat,More severe or more likely to occur,"""We detect the dominant influence of anthropog...",2007,"Jones, G. et al., 2007: Human contribution to ...",Journal of Geophysical Research: Atmospheres,No,https://agupubs.onlinelibrary.wiley.com/doi/fu...
4,Moscow summer heatwave,2010,2010,Event,RUS,Europe,Heat,More severe or more likely to occur,"""For July temperature in Moscow, we estimate.....",2011,"Rahmstorf, S. & Coumou, D. 2011: Increase of e...",Proceedings of the National Academy of Sciences,No,http://www.pnas.org/content/108/44/17905.abstract
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,China growing season hot and dry events,mid 1990s,Mid-1990s,Event,CHN,Eastern and south-eastern Asia,Compound,More severe or more likely to occur,"""Anthropogenic forcing changes can explain 60%...",2024,"Su Q. et al., 2024: Anthropogenic Influence on...",Advances in Atmospheric Sciences,No,https://doi.org/10.1007/s00376-023-2319-z
740,China hot-wet events,1979-2014,NaN,Trend,CHN,Eastern and south-eastern Asia,Compound,"Decrease, less severe or less likely to occur","""Over the past 40 years, anthropogenic activit...",2024,"Yao H. et al., 2024: Changes caused by human a...",Communications Earth & Environment,No,https://doi.org/10.1038/s43247-024-01625-y
741,Heat extremes behind bleaching of the Great Ba...,"2020, 2024","2017, 2020, 2024",Event,AUS,Australia and New Zealand,Impact,More severe or more likely to occur,"""Climate model analysis confirms that human in...",2024,"Henley B.J. et al., 2024: Highest ocean heat i...",Nature,No,https://doi.org/10.1038/s41586-024-07672-x
742,Heat-related neonatal deaths in low- and middl...,2001-2019,NaN,Trend,NaN,Global,Impact,More severe or more likely to occur,"""Climate change was responsible for 32% (range...",2024,"Dimitrova. A. et al., 2024: Temperature-relate...",Nature Communications,No,https://www.nature.com/articles/s41467-024-498...
743,Hospitalisations in China due to heat,2000-2019,NaN,Trend,CHN,Eastern and south-eastern Asia,Impact,More severe or more likely to occur,"""In the 2010s, the heat-related attributable f...",2024,"Zhou. L. et al,. 2024: Quantification of the H...",Environmental Health Perspectives,No,https://ehp.niehs.nih.gov/doi/10.1289/EHP14057